// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package clean_mock

import (
	"context"

	"github.com/int128/kubelogin/pkg/usecases/clean"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	_ = "STUB: not implemented"
	return nil
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter { _ = "STUB: not implemented"; return nil }

// Do provides a mock function for the type MockInterface
func (_mock *MockInterface) Do(ctx context.Context, in clean.Input) error {
	_ = "STUB: not implemented"
	return nil
}

// MockInterface_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockInterface_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - in clean.Input
func (_e *MockInterface_Expecter) Do(ctx interface{}, in interface{}) *MockInterface_Do_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Do_Call) Run(run func(ctx context.Context, in clean.Input)) *MockInterface_Do_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Do_Call) Return(err error) *MockInterface_Do_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Do_Call) RunAndReturn(run func(ctx context.Context, in clean.Input) error) *MockInterface_Do_Call {
	_ = "STUB: not implemented"
	return nil
}
