// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package logger_mock

import (
	"github.com/int128/kubelogin/pkg/infrastructure/logger"
	"github.com/spf13/pflag"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	_ = "STUB: not implemented"
	return nil
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter { _ = "STUB: not implemented"; return nil }

// AddFlags provides a mock function for the type MockInterface
func (_mock *MockInterface) AddFlags(f *pflag.FlagSet) { _ = "STUB: not implemented"; return }

// MockInterface_AddFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFlags'
type MockInterface_AddFlags_Call struct {
	*mock.Call
}

// AddFlags is a helper method to define mock.On call
//   - f *pflag.FlagSet
func (_e *MockInterface_Expecter) AddFlags(f interface{}) *MockInterface_AddFlags_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_AddFlags_Call) Run(run func(f *pflag.FlagSet)) *MockInterface_AddFlags_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_AddFlags_Call) Return() *MockInterface_AddFlags_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_AddFlags_Call) RunAndReturn(run func(f *pflag.FlagSet)) *MockInterface_AddFlags_Call {
	_ = "STUB: not implemented"
	return nil

	// IsEnabled provides a mock function for the type MockInterface
}

func (_mock *MockInterface) IsEnabled(level int) bool { _ = "STUB: not implemented"; return false }

// MockInterface_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockInterface_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
//   - level int
func (_e *MockInterface_Expecter) IsEnabled(level interface{}) *MockInterface_IsEnabled_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_IsEnabled_Call) Run(run func(level int)) *MockInterface_IsEnabled_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_IsEnabled_Call) Return(b bool) *MockInterface_IsEnabled_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_IsEnabled_Call) RunAndReturn(run func(level int) bool) *MockInterface_IsEnabled_Call {
	_ = "STUB: not implemented"
	return nil
}

// Printf provides a mock function for the type MockInterface
func (_mock *MockInterface) Printf(format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// MockInterface_Printf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Printf'
type MockInterface_Printf_Call struct {
	*mock.Call
}

// Printf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockInterface_Expecter) Printf(format interface{}, args ...interface{}) *MockInterface_Printf_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Printf_Call) Run(run func(format string, args ...interface{})) *MockInterface_Printf_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Printf_Call) Return() *MockInterface_Printf_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Printf_Call) RunAndReturn(run func(format string, args ...interface{})) *MockInterface_Printf_Call {
	_ = "STUB: not implemented"
	return nil

	// V provides a mock function for the type MockInterface
}

func (_mock *MockInterface) V(level int) logger.Verbose {
	_ = "STUB: not implemented"
	return *new(logger.Verbose)
}

// MockInterface_V_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'V'
type MockInterface_V_Call struct {
	*mock.Call
}

// V is a helper method to define mock.On call
//   - level int
func (_e *MockInterface_Expecter) V(level interface{}) *MockInterface_V_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_V_Call) Run(run func(level int)) *MockInterface_V_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_V_Call) Return(verbose logger.Verbose) *MockInterface_V_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_V_Call) RunAndReturn(run func(level int) logger.Verbose) *MockInterface_V_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewMockVerbose creates a new instance of MockVerbose. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerbose(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerbose {
	_ = "STUB: not implemented"
	return nil
}

// MockVerbose is an autogenerated mock type for the Verbose type
type MockVerbose struct {
	mock.Mock
}

type MockVerbose_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerbose) EXPECT() *MockVerbose_Expecter { _ = "STUB: not implemented"; return nil }

// Infof provides a mock function for the type MockVerbose
func (_mock *MockVerbose) Infof(format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// MockVerbose_Infof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infof'
type MockVerbose_Infof_Call struct {
	*mock.Call
}

// Infof is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockVerbose_Expecter) Infof(format interface{}, args ...interface{}) *MockVerbose_Infof_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockVerbose_Infof_Call) Run(run func(format string, args ...interface{})) *MockVerbose_Infof_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockVerbose_Infof_Call) Return() *MockVerbose_Infof_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockVerbose_Infof_Call) RunAndReturn(run func(format string, args ...interface{})) *MockVerbose_Infof_Call {
	_ = "STUB: not implemented"
	return nil

	// newMockgoLogger creates a new instance of mockgoLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
	// The first argument is typically a *testing.T value.
}

func newMockgoLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockgoLogger {
	_ = "STUB: not implemented"
	return nil
}

// mockgoLogger is an autogenerated mock type for the goLogger type
type mockgoLogger struct {
	mock.Mock
}

type mockgoLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *mockgoLogger) EXPECT() *mockgoLogger_Expecter { _ = "STUB: not implemented"; return nil }

// Printf provides a mock function for the type mockgoLogger
func (_mock *mockgoLogger) Printf(format string, v ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// mockgoLogger_Printf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Printf'
type mockgoLogger_Printf_Call struct {
	*mock.Call
}

// Printf is a helper method to define mock.On call
//   - format string
//   - v ...interface{}
func (_e *mockgoLogger_Expecter) Printf(format interface{}, v ...interface{}) *mockgoLogger_Printf_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockgoLogger_Printf_Call) Run(run func(format string, v ...interface{})) *mockgoLogger_Printf_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockgoLogger_Printf_Call) Return() *mockgoLogger_Printf_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockgoLogger_Printf_Call) RunAndReturn(run func(format string, v ...interface{})) *mockgoLogger_Printf_Call {
	_ = "STUB: not implemented"
	return nil
}
