// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package stdio_mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStdout creates a new instance of MockStdout. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStdout(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStdout {
	_ = "STUB: not implemented"
	return nil
}

// MockStdout is an autogenerated mock type for the Stdout type
type MockStdout struct {
	mock.Mock
}

type MockStdout_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStdout) EXPECT() *MockStdout_Expecter { _ = "STUB: not implemented"; return nil }

// Write provides a mock function for the type MockStdout
func (_mock *MockStdout) Write(p []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

// MockStdout_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockStdout_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *MockStdout_Expecter) Write(p interface{}) *MockStdout_Write_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockStdout_Write_Call) Run(run func(p []byte)) *MockStdout_Write_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockStdout_Write_Call) Return(n int, err error) *MockStdout_Write_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockStdout_Write_Call) RunAndReturn(run func(p []byte) (int, error)) *MockStdout_Write_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewMockStdin creates a new instance of MockStdin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStdin(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStdin {
	_ = "STUB: not implemented"
	return nil
}

// MockStdin is an autogenerated mock type for the Stdin type
type MockStdin struct {
	mock.Mock
}

type MockStdin_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStdin) EXPECT() *MockStdin_Expecter { _ = "STUB: not implemented"; return nil }

// Read provides a mock function for the type MockStdin
func (_mock *MockStdin) Read(p []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

// MockStdin_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockStdin_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *MockStdin_Expecter) Read(p interface{}) *MockStdin_Read_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockStdin_Read_Call) Run(run func(p []byte)) *MockStdin_Read_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockStdin_Read_Call) Return(n int, err error) *MockStdin_Read_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockStdin_Read_Call) RunAndReturn(run func(p []byte) (int, error)) *MockStdin_Read_Call {
	_ = "STUB: not implemented"
	return nil
}
