// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package io_mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCloser creates a new instance of MockCloser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCloser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCloser {
	_ = "STUB: not implemented"
	return nil
}

// MockCloser is an autogenerated mock type for the Closer type
type MockCloser struct {
	mock.Mock
}

type MockCloser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCloser) EXPECT() *MockCloser_Expecter { _ = "STUB: not implemented"; return nil }

// Close provides a mock function for the type MockCloser
func (_mock *MockCloser) Close() error { _ = "STUB: not implemented"; return nil }

// MockCloser_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCloser_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockCloser_Expecter) Close() *MockCloser_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockCloser_Close_Call) Run(run func()) *MockCloser_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockCloser_Close_Call) Return(err error) *MockCloser_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockCloser_Close_Call) RunAndReturn(run func() error) *MockCloser_Close_Call {
	_ = "STUB: not implemented"
	return nil
}
