// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jwt_mock

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClock creates a new instance of MockClock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClock {
	_ = "STUB: not implemented"
	return nil
}

// MockClock is an autogenerated mock type for the Clock type
type MockClock struct {
	mock.Mock
}

type MockClock_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClock) EXPECT() *MockClock_Expecter { _ = "STUB: not implemented"; return nil }

// Now provides a mock function for the type MockClock
func (_mock *MockClock) Now() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

// MockClock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockClock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockClock_Expecter) Now() *MockClock_Now_Call { _ = "STUB: not implemented"; return nil }

func (_c *MockClock_Now_Call) Run(run func()) *MockClock_Now_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClock_Now_Call) Return(time1 time.Time) *MockClock_Now_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClock_Now_Call) RunAndReturn(run func() time.Time) *MockClock_Now_Call {
	_ = "STUB: not implemented"
	return nil
}
