// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package browser_mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	_ = "STUB: not implemented"
	return nil
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter { _ = "STUB: not implemented"; return nil }

// Open provides a mock function for the type MockInterface
func (_mock *MockInterface) Open(url string) error { _ = "STUB: not implemented"; return nil }

// MockInterface_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockInterface_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - url string
func (_e *MockInterface_Expecter) Open(url interface{}) *MockInterface_Open_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Open_Call) Run(run func(url string)) *MockInterface_Open_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Open_Call) Return(err error) *MockInterface_Open_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Open_Call) RunAndReturn(run func(url string) error) *MockInterface_Open_Call {
	_ = "STUB: not implemented"
	return nil
}

// OpenCommand provides a mock function for the type MockInterface
func (_mock *MockInterface) OpenCommand(ctx context.Context, url string, command string) error {
	_ = "STUB: not implemented"
	return nil
}

// MockInterface_OpenCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenCommand'
type MockInterface_OpenCommand_Call struct {
	*mock.Call
}

// OpenCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - command string
func (_e *MockInterface_Expecter) OpenCommand(ctx interface{}, url interface{}, command interface{}) *MockInterface_OpenCommand_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_OpenCommand_Call) Run(run func(ctx context.Context, url string, command string)) *MockInterface_OpenCommand_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_OpenCommand_Call) Return(err error) *MockInterface_OpenCommand_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_OpenCommand_Call) RunAndReturn(run func(ctx context.Context, url string, command string) error) *MockInterface_OpenCommand_Call {
	_ = "STUB: not implemented"
	return nil
}
