// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"os"

	"github.com/int128/kubelogin/pkg/cmd"
	"github.com/int128/kubelogin/pkg/infrastructure/browser"
	"github.com/int128/kubelogin/pkg/infrastructure/clock"
	"github.com/int128/kubelogin/pkg/infrastructure/logger"
	"github.com/int128/kubelogin/pkg/infrastructure/stdio"
)

// Injectors from di.go:

// NewCmd returns an instance of infrastructure.Cmd.
func NewCmd() cmd.Interface { _ = "STUB: not implemented"; return *new(cmd.Interface) }

var (
	_wireFileValue   = os.Stdin
	_wireOsFileValue = os.Stdout
)

// NewCmdForHeadless returns an instance of infrastructure.Cmd for headless testing.
func NewCmdForHeadless(clockInterface clock.Interface, stdin stdio.Stdin, stdout stdio.Stdout, loggerInterface logger.Interface, browserInterface browser.Interface) cmd.Interface {
	_ = "STUB: not implemented"
	return *new(cmd.Interface)
}
