// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reader_mock

import (
	"github.com/int128/kubelogin/pkg/credentialplugin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	_ = "STUB: not implemented"
	return nil
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter { _ = "STUB: not implemented"; return nil }

// Read provides a mock function for the type MockInterface
func (_mock *MockInterface) Read() (credentialplugin.Input, error) {
	_ = "STUB: not implemented"
	return *new(credentialplugin.Input), nil
}

// MockInterface_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockInterface_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *MockInterface_Expecter) Read() *MockInterface_Read_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Read_Call) Run(run func()) *MockInterface_Read_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Read_Call) Return(input credentialplugin.Input, err error) *MockInterface_Read_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Read_Call) RunAndReturn(run func() (credentialplugin.Input, error)) *MockInterface_Read_Call {
	_ = "STUB: not implemented"
	return nil
}
