package keypair

import (
	"crypto/tls"
)

// KeyPair represents a pair of certificate and key.
type KeyPair struct {
	CertPath     string
	KeyPath      string
	CACertPath   string
	CACertBase64 string
	TLSConfig    *tls.Config
}

// None represents non-TLS.
var None KeyPair

// Server is a KeyPair for TLS server.
// These files should be generated by Makefile before test.
var Server = KeyPair{
	CertPath:     "keypair/testdata/server.crt",
	KeyPath:      "keypair/testdata/server.key",
	CACertPath:   "keypair/testdata/ca.crt",
	CACertBase64: readAsBase64("keypair/testdata/ca.crt"),
	TLSConfig:    newTLSConfig("keypair/testdata/ca.crt"),
}

func readAsBase64(name string) string { _ = "STUB: not implemented"; return "" }

func newTLSConfig(name string) *tls.Config { _ = "STUB: not implemented"; return nil }
