// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package clock_mock

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	_ = "STUB: not implemented"
	return nil
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter { _ = "STUB: not implemented"; return nil }

// Now provides a mock function for the type MockInterface
func (_mock *MockInterface) Now() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

// MockInterface_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockInterface_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockInterface_Expecter) Now() *MockInterface_Now_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Now_Call) Run(run func()) *MockInterface_Now_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Now_Call) Return(time1 time.Time) *MockInterface_Now_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockInterface_Now_Call) RunAndReturn(run func() time.Time) *MockInterface_Now_Call {
	_ = "STUB: not implemented"
	return nil
}
