// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package logger_mock

import (
	mock "github.com/stretchr/testify/mock"
)

// newMocktestingLogger creates a new instance of mocktestingLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktestingLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktestingLogger {
	_ = "STUB: not implemented"
	return nil
}

// mocktestingLogger is an autogenerated mock type for the testingLogger type
type mocktestingLogger struct {
	mock.Mock
}

type mocktestingLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktestingLogger) EXPECT() *mocktestingLogger_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// Logf provides a mock function for the type mocktestingLogger
func (_mock *mocktestingLogger) Logf(format string, v ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// mocktestingLogger_Logf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logf'
type mocktestingLogger_Logf_Call struct {
	*mock.Call
}

// Logf is a helper method to define mock.On call
//   - format string
//   - v ...interface{}
func (_e *mocktestingLogger_Expecter) Logf(format interface{}, v ...interface{}) *mocktestingLogger_Logf_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocktestingLogger_Logf_Call) Run(run func(format string, v ...interface{})) *mocktestingLogger_Logf_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocktestingLogger_Logf_Call) Return() *mocktestingLogger_Logf_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocktestingLogger_Logf_Call) RunAndReturn(run func(format string, v ...interface{})) *mocktestingLogger_Logf_Call {
	_ = "STUB: not implemented"
	return nil
}
